
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clttmlssqtcevkteqgie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsdHRtbHNzcXRjZXZrdGVxZ2llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNDcwMjcsImV4cCI6MjA1NjYyMzAyN30.QdLsWmKVukUhtT4JXKOCBpn_KTEr1FW_OS-UmCIzZn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
